# Generated by Django 5.2.4 on 2025-07-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('cost_centres', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costcentre',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cost Centre', 'verbose_name_plural': 'Cost Centres'},
        ),
        migrations.AlterUniqueTogether(
            name='costcentre',
            unique_together={('company', 'name')},
        ),
        migrations.AddField(
            model_name='costcentre',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes or description for the cost centre'),
        ),
        migrations.AddField(
            model_name='costcentre',
            name='transaction_direction',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit'), ('Both', 'Both')], default='Both', help_text='Allowed transaction direction: Credit, Debit, or Both', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='costcentre',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp of the last update to this cost centre'),
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp of when this cost centre was created'),
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag; inactive cost centres are not shown in active listings'),
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='name',
            field=models.CharField(help_text='Descriptive name of the cost centre', max_length=255),
        ),
        migrations.RemoveField(
            model_name='costcentre',
            name='code',
        ),
        migrations.RemoveField(
            model_name='costcentre',
            name='description',
        ),
    ]
