# Generated by Django 5.2.4 on 2025-07-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_centres', '0002_alter_costcentre_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costcentre',
            name='id',
        ),
        migrations.AddField(
            model_name='costcentre',
            name='cost_centre_id',
            field=models.AutoField(help_text='Unique identifier for the cost centre', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='transaction_direction',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit'), ('Both', 'Both')], default='Both', help_text='Allowed transaction direction: Credit, Debit, or Both', max_length=10),
        ),
    ]
