# Generated by Django 5.2.4 on 2025-07-05 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('cost_centres', '0003_remove_costcentre_id_costcentre_cost_centre_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcentre',
            name='company',
            field=models.ForeignKey(help_text='Company this cost centre belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='cost_centres', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when this cost centre was created'),
        ),
        migrations.AlterField(
            model_name='costcentre',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when this cost centre was last updated'),
        ),
    ]
