# Generated by Django 5.2.4 on 2025-07-07 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_remove_company_updated_at_and_more'),
        ('projects', '0001_initial'),
        ('properties', '0008_alter_property_address_line1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Asset name', max_length=255)),
                ('category', models.CharField(help_text='Asset category', max_length=255)),
                ('purchase_date', models.DateField(help_text='Date of purchase')),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Purchase price', max_digits=12)),
                ('warranty_expiry', models.DateField(blank=True, help_text='Warranty expiration date', null=True)),
                ('location', models.CharField(help_text='Physical location of the asset', max_length=255)),
                ('maintenance_frequency', models.CharField(help_text='Frequency of maintenance (e.g., monthly)', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the asset')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when asset was created')),
                ('company', models.ForeignKey(help_text='Company that owns this asset', on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='companies.company')),
                ('project', models.ForeignKey(blank=True, help_text='Linked project, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='projects.project')),
                ('property', models.ForeignKey(blank=True, help_text='Linked property, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='properties.property')),
            ],
        ),
        migrations.CreateModel(
            name='AssetDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Uploaded document file', upload_to='asset_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when document was uploaded')),
                ('asset', models.ForeignKey(help_text='Linked asset for this document', on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assets.asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetServiceDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(help_text='Date when service is due')),
                ('description', models.CharField(help_text='Service description', max_length=255)),
                ('completed', models.BooleanField(default=False, help_text='Mark if the service was completed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this service due was created')),
                ('asset', models.ForeignKey(help_text='Linked asset for this service due', on_delete=django.db.models.deletion.CASCADE, related_name='service_dues', to='assets.asset')),
            ],
        ),
    ]
