# Generated by Django 5.2.4 on 2025-07-05 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='id',
        ),
        migrations.AddField(
            model_name='property',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this property belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='companies.company'),
        ),
        migrations.AddField(
            model_name='property',
            name='property_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='property',
            name='expected_rent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected monthly rent', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(help_text='Property location', max_length=512),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(help_text='Property name', max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='project',
            field=models.ForeignKey(help_text='Project this property is part of', on_delete=django.db.models.deletion.CASCADE, related_name='site_properties', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='property',
            name='purchase_date',
            field=models.DateField(help_text='Date of purchase'),
        ),
        migrations.AlterField(
            model_name='property',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, help_text='Purchase price of the property', max_digits=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('inactive', 'Inactive')], default='active', help_text='Current status of the property', max_length=20),
        ),
    ]
