# Generated by Django 5.2.4 on 2025-07-05 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '0001_initial'),
        ('properties', '0002_remove_property_id_property_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='property_id',
        ),
        migrations.AddField(
            model_name='property',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='property',
            name='company',
            field=models.ForeignKey(default=2, help_text='Company owning this property', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='companies.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='expected_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_properties', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='property',
            name='purchase_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('sold', 'Sold'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
