# Generated by Django 5.2.4 on 2025-07-06 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default='Unknown', help_text='Property location', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='purchase_date',
            field=models.DateField(default='2000-01-01', help_text='Purchase date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Purchase price', max_digits=15),
            preserve_default=False,
        ),
    ]
