# Generated by Django 5.2.4 on 2025-07-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_location_property_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether the property is active (visible) or inactive (hidden)'),
        ),
    ]
