# Generated by Django 5.2.4 on 2025-07-07 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_company_updated_at_and_more'),
        ('properties', '0007_property_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='build_up_area_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='property',
            name='config_bathroom',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='config_bhk',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='expected_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='expected_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='igen_service_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_area_cents',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='lease_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='lease_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='next_inspection_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='pincode',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('villa', 'Villa'), ('plot', 'Plot')], max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='purchase_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='property',
            name='purpose',
            field=models.CharField(choices=[('rental', 'Rental'), ('sale', 'Sale'), ('care', 'Care')], max_length=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(default='Kerala', max_length=100),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('vacant', 'Vacant'), ('occupied', 'Occupied'), ('sold', 'Sold'), ('not_for_rent', 'Not for Rent')], default='vacant', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='file_url',
            field=models.FileField(upload_to='property_docs/'),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='uploaded_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='propertykeydate',
            name='date_label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='propertykeydate',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='propertykeydate',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_dates', to='properties.property'),
        ),
        migrations.AlterField(
            model_name='propertykeydate',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
