# Generated by Django 5.2.4 on 2025-07-06 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_updated_at_companydocument_document_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='companydocument',
            name='document_name',
        ),
        migrations.AlterField(
            model_name='company',
            name='mca',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
