# Generated by Django 5.2.3 on 2025-07-07 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('projects', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('entity_id', models.AutoField(help_text='Unique identifier for the entity', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the entity', max_length=255)),
                ('entity_type', models.CharField(choices=[('Property', 'Property'), ('Project', 'Project'), ('Internal', 'Internal')], help_text='Entity type: Property, Project, or Internal', max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Entity status: Active or Inactive', max_length=10)),
                ('remarks', models.TextField(blank=True, help_text='Optional remarks about the entity')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the entity was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated')),
                ('company', models.ForeignKey(blank=True, help_text='Company this entity belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='companies.company')),
                ('linked_project', models.ForeignKey(blank=True, help_text='Linked project if entity_type=Project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project')),
            ],
            options={
                'verbose_name': 'Entity',
                'verbose_name_plural': 'Entities',
                'ordering': ['-created_at'],
            },
        ),
    ]
