# Generated by Django 5.2.4 on 2025-07-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['-created_at'], 'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
        migrations.RemoveField(
            model_name='entity',
            name='id',
        ),
        migrations.AddField(
            model_name='entity',
            name='entity_id',
            field=models.AutoField(help_text='Unique identifier for the entity', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='entity',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Soft delete flag; inactive entities are hidden'),
        ),
        migrations.AddField(
            model_name='entity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the entity was last updated'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='address',
            field=models.TextField(blank=True, help_text="Entity's address"),
        ),
        migrations.AlterField(
            model_name='entity',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the entity was created'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('Client', 'Client'), ('Vendor', 'Vendor'), ('Partner', 'Partner')], help_text='Type of entity: Client, Vendor, or Partner', max_length=20),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(help_text='Unique name of the entity', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the entity'),
        ),
    ]
