# Generated by Django 5.2.3 on 2025-07-07 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='linked_property',
            field=models.ForeignKey(blank=True, help_text='Linked property if entity_type=Property', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property'),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('company', 'name')},
        ),
    ]
