# Generated by Django 5.2.4 on 2025-07-05 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('entities', '0002_alter_entity_options_remove_entity_id_and_more'),
        ('projects', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='address',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='contact_phone',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='notes',
        ),
        migrations.AddField(
            model_name='entity',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company this entity belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='companies.company'),
        ),
        migrations.AddField(
            model_name='entity',
            name='linked_project',
            field=models.ForeignKey(blank=True, help_text='Linked project if entity_type=Project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
        migrations.AddField(
            model_name='entity',
            name='linked_property',
            field=models.ForeignKey(blank=True, help_text='Linked property if entity_type=Property', null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.property'),
        ),
        migrations.AddField(
            model_name='entity',
            name='remarks',
            field=models.TextField(blank=True, help_text='Optional remarks about the entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Entity status: Active or Inactive', max_length=10),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('Property', 'Property'), ('Project', 'Project'), ('Internal', 'Internal')], help_text='Entity type: Property, Project, or Internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(help_text='Name of the entity', max_length=255),
        ),
    ]
