# Generated by Django 5.2.4 on 2025-07-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('entities', '0003_remove_entity_address_remove_entity_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('company', 'name')},
        ),
    ]
