# Generated by Django 5.2.4 on 2025-07-05 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cost_centres', '0004_alter_costcentre_company_alter_costcentre_created_at_and_more'),
        ('transaction_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactiontype',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transaction Type', 'verbose_name_plural': 'Transaction Types'},
        ),
        migrations.RemoveField(
            model_name='transactiontype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transactiontype',
            name='id',
        ),
        migrations.RemoveField(
            model_name='transactiontype',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='transactiontype',
            name='type',
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='cost_centre',
            field=models.ForeignKey(blank=True, help_text='Cost centre linked to this transaction type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_types', to='cost_centres.costcentre'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='direction',
            field=models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], default='Credit', help_text='Transaction direction: Credit or Debit', max_length=10),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='gst_applicable',
            field=models.BooleanField(default=False, help_text='Whether GST is applicable for this transaction type'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='remarks',
            field=models.TextField(blank=True, help_text='Optional remarks about the transaction type'),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', help_text='Status of the transaction type: Active or Inactive', max_length=10),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='transaction_type_id',
            field=models.AutoField(help_text='Unique identifier for the transaction type', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the transaction type was last updated'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the transaction type was created'),
        ),
        migrations.AlterField(
            model_name='transactiontype',
            name='name',
            field=models.CharField(help_text='Descriptive name of the transaction type', max_length=255),
        ),
    ]
